In [ ]:
# Question 2: Extract Transaction IDs (Easy)Extract all transaction_id values as a 1D NumPy array.Hint: Use array slicing or column selection

In [4]:
import numpy as np
data = np.array([
    [101, 5000],
    [102, 7000],
    [103, 9000]
])
res = data[:,0]
res

array([101, 102, 103])

In [ ]:
# Question 3: Get Array Shape (Easy)Find the shape, size, and dimensions of the retail data array.Hint: Use .shape, .size, .ndim

In [10]:
import numpy as np
data = np.array([
    [101, 5000],
    [102, 7000],
    [103, 9000]
])

print("shape",data.shape)
print("size",data.size)
print("dimensions",data.ndim)

shape (3, 2)
size 6
dimensions 2


In [ ]:
# Question 4: Data Types (Easy)Check the data type of each column in the array.Hint: Use .dtype attribute

In [12]:
import numpy as np
data = np.array([
    [101, 5000],
    [102, 7000],
    [103, 9000]
])
print(data.dtype)

int32


In [ ]:
# Question 5: Create Quantity Array (Easy)Create a NumPy array containing only the quantity column.Hint: Index or slice the specific column

In [18]:
import numpy as np
data = np.array([
    [101, 5000],
    [102, 7000],
    [103, 9000]
])
res = data[:1]
res

array([[ 101, 5000]])

In [ ]:
# Question 6: Create Price Array (Easy)Extract unit_price values as a separate array.Hint: Similar to previous

In [17]:
import numpy as np
data = np.array([
    [101, 5, 200],
    [102, 7, 150],
    [103, 9, 300]
])
res = data[:2]
print(res)

[[101   5 200]
 [102   7 150]]


In [ ]:
# Question 7: First 10 Transactions (Easy)Get the first 10 rows of data.Hint: Use array slicing [:10]

In [16]:
import numpy as np
data = np.array([
    [101, 5, 200],
    [102, 7, 150],
    [103, 9, 300],
    [104, 4, 250],
    [105, 6, 180]
])
res = data[:10]
print(res)

[[101   5 200]
 [102   7 150]
 [103   9 300]
 [104   4 250]
 [105   6 180]]
